import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Leonard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <h1>Leonard</h1> 
        <ul>
          <a href="">Sign up</a>
        </ul>
      </nav>
      <main className={styles.main}>
        <section>
          <h1>Keep Your Discord In The Loop</h1>
          <h2>Life can get busy. Let Leonard lighten the load by keeping track of your team's game night. </h2>
          <button>Add To Discord</button>
        </section>
        <section>
          <div>
            <h1>Reminders on your schedule</h1>
            <p>Whether you want to remind your server of a one off session or a weekly raid, Leonard is equipped to handle it.</p>
          </div>
          <div>
            <h1>Have to cancel? No problem!</h1>
            <p>Mark an event as cancelled and let Leonard break the bad news. If the event is weekly you can cancel it one week without needing to set it back up for the next. </p>
          </div>
          <div>
            <h1>Set reminders on our website or your server</h1>
            <p>You can set detailed reminders through the website, but you can also use bot commands if you'd prefer. </p>
          </div>
        </section>
        <section>
          <h1>Frequently Asked Questions</h1>
          <div>
            <div>
              <h2>Is it good</h2>
            </div>
            <div>
              <p>Yes</p>
            </div>
          </div>
          <div>
            <div>
              <h2>Is it good</h2>
            </div>
            <div>
              <p>Yes</p>
            </div>
          </div>
          <div>
            <div>
              <h2>Is it good</h2>
            </div>
            <div>
              <p>Yes</p>
            </div>
          </div>
          <div>
            <div>
              <h2>Is it good</h2>
            </div>
            <div>
              <p>Yes</p>
            </div>
          </div>
          <div>
            <div>
              <h2>Is it good</h2>
            </div>
            <div>
              <p>Yes</p>
            </div>
          </div>
        </section>
        <section>
          <button>Add To Discord</button>
        </section>
        <footer>
          <span>This is a footer</span>
        </footer>
      </main>
    </div>
  )
}
